### ISSUE TITLE
Fatal error: Call to undefined function curl_init() 

### ISSUE THREAD

**Issue by VineethKumar7** [suyashbansal/Way2SMS-API-1#3]
Fatal error: Call to undefined function curl_init() in C:\wamp\www\geekay\Waytosms\Way2SMS-API-master\way2sms-api.php on line 18
Please help me..

**Comment by suyashbansal** [comment]
curl is an extension that needs to be activated. Since you are running it through WAMP, you should refer [this stackoverflow solution](http://stackoverflow.com/questions/10939248/php-curl-not-working-wamp-on-windows-7-64-bit#answer-10977022) to get working.

You can also check this [video](https://www.youtube.com/watch?v=7qNTi1sEfE8) but it's not in english :smile:
